const KEY="papelaria_v2";let db=JSON.parse(localStorage.getItem(KEY)||'{"orders":[],"next":1}');
const settings=JSON.parse(localStorage.getItem("papelaria_v2_settings")||'{"interval":1200000}');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function save(){localStorage.setItem(KEY,JSON.stringify(db))}
function go(v){$$(".view").forEach(x=>x.classList.add("hidden"));$("#"+v).classList.remove("hidden");$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===v));$("#title").textContent={home:"REGISTRO DE COMANDAS",new:"REGISTRAR COMANDA",orders:"TODAS AS COMANDAS",production:"FILA DE PRODUÇÃO",alerts:"CENTRAL DE ALERTAS",search:"PESQUISAR"}[v];render()}
$$(".nav").forEach(b=>b.onclick=()=>go(b.dataset.view));$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
function lines(){let a=[];$$(".service").forEach(i=>{let q=+i.value||0;if(q)a.push({name:i.dataset.name,qty:q,price:+i.dataset.price,total:q*(+i.dataset.price)})});let q=+$("#bindQty").value||0,p=+$("#bindPrice").value||0,t=$("#bindType").value;if(q&&t)a.push({name:"Encadernação "+t,qty:q,price:p,total:q*p,sheets:+$("#bindSheets").value||0});return a}
function calc(){let a=lines(),t=a.reduce((s,x)=>s+x.total,0);$("#total").textContent=money(t);let r=+$("#received").value||0;$("#change").textContent=money(Math.max(0,r-t))}
$$(".service,#bindQty,#bindPrice,#bindSheets,#received,#bindType").forEach(x=>x.addEventListener("input",calc));$("#bindType").addEventListener("change",calc);
function clearForm(){$("#customer").value="";$("#phone").value="";$("#notes").value="";$("#received").value=0;$("#bindSheets").value=0;$("#bindQty").value=0;$("#bindPrice").value=6;$("#bindType").selectedIndex=0;$$(".service").forEach(x=>x.value=0);$("#nextNumber").textContent="#"+String(db.next).padStart(4,"0");calc()}
$("#create").onclick=()=>{let customer=$("#customer").value.trim(),ls=lines();if(!customer)return toast("Informe o nome do cliente.");if(!ls.length)return toast("Adicione pelo menos um serviço.");let total=ls.reduce((s,x)=>s+x.total,0),o={id:Date.now(),number:db.next++,customer,phone:$("#phone").value,customerType:$("#customerType").value,payment:$("#payment").value,services:ls,total,received:+$("#received").value||0,notes:$("#notes").value.trim(),status:"open",createdAt:Date.now(),paidAt:null,lastAlarm:null,alarmCount:0,completedAt:null};db.orders.unshift(o);save();clearForm();go("home");toast("Comanda #"+o.number+" registrada.")};
function pay(id){let o=db.orders.find(x=>x.id===id);o.status="paid";o.paidAt=Date.now();o.lastAlarm=Date.now();o.alarmCount=0;save();render();toast("🟢 Pagamento confirmado. O alarme de 20 em 20 minutos começou.")}
function done(id){let o=db.orders.find(x=>x.id===id);o.status="done";o.completedAt=Date.now();save();render();toast("✓ Comanda concluída. Alarmes encerrados.")}
function row(o){let st=o.status==="open"?["open","AGUARDANDO PAGAMENTO"]:o.status==="paid"?(o.alarmCount?["alert","🔔 ALERTA ATIVO"]:["paid","PAGO / PRODUÇÃO"]):["done","CONCLUÍDA"];let act=o.status==="open"?`<button class="small-btn ok" onclick="pay(${o.id})">CONFIRMAR PAGAMENTO</button>`:o.status==="paid"?`<button class="small-btn ok" onclick="done(${o.id})">CONCLUIR</button>`:"";return `<tr><td class="id">#${String(o.number).padStart(4,"0")}</td><td><b>${esc(o.customer)}</b><br><small>${o.services.map(x=>esc(x.name)+" × "+x.qty).join(" • ")}</small></td><td>${money(o.total)}</td><td><span class="status ${st[0]}">${st[1]}</span></td><td>${act}</td></tr>`}
function table(arr){return arr.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Nº</th><th>CLIENTE / SERVIÇOS</th><th>TOTAL</th><th>STATUS</th><th>AÇÕES</th></tr></thead><tbody>${arr.map(row).join("")}</tbody></table></div>`:'<div class="empty">Nenhum registro encontrado.</div>'}
function render(){let all=db.orders,prod=all.filter(x=>x.status==="paid"),alerts=prod.filter(x=>x.alarmCount>0),done=all.filter(x=>x.status==="done");$("#sTotal").textContent=all.length;$("#sProduction").textContent=prod.length;$("#sAlerts").textContent=alerts.length;$("#sDone").textContent=done.length;$("#homeTable").innerHTML=table(all.slice(0,10));$("#allTable").innerHTML=table(all);$("#productionTable").innerHTML=table(prod);$("#alertTable").innerHTML=table(alerts);$("#nextNumber").textContent="#"+String(db.next).padStart(4,"0");search()}
function search(){let q=($("#searchBox")?.value||"").toLowerCase();if($("#searchResults"))$("#searchResults").innerHTML=table(db.orders.filter(o=>!q||String(o.number).includes(q)||o.customer.toLowerCase().includes(q)||o.services.some(s=>s.name.toLowerCase().includes(q))))}
$("#searchBox").addEventListener("input",search);
function toast(t,alarm=false){let x=$("#toast");x.textContent=t;x.className="toast"+(alarm?" alarm":"");clearTimeout(window.tt);window.tt=setTimeout(()=>x.classList.add("hidden"),6000)}
async function alarm(o){toast(`🔔 COMANDA #${o.number} ainda não foi concluída!`,true);if("Notification"in window&&Notification.permission==="granted"){try{new Notification(`Comanda #${o.number} pendente`,{body:`${o.customer}: produção ainda não concluída.`})}catch{}}}
function tick(){let now=Date.now(),changed=false;db.orders.filter(o=>o.status==="paid").forEach(o=>{let base=o.lastAlarm||o.paidAt;if(now-base>=settings.interval){o.alarmCount++;o.lastAlarm=now;changed=true;alarm(o)}});if(changed)save();render()}
$("#exportCsv").onclick=()=>{let csv="Numero,Cliente,Total,Status,Criada\\n"+db.orders.map(o=>[o.number,'"'+o.customer.replaceAll('"','""')+'"',o.total,o.status,new Date(o.createdAt).toLocaleString("pt-BR")].join(",")).join("\\n");let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="comandas.csv";a.click()}
setInterval(()=>$("#clock").textContent=new Date().toLocaleString("pt-BR"),1000);setInterval(tick,1000);calc();render()
